import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";

import { getWeatherDataByLocation, getWeatherDataByUserLocation } from "./weatherAPI";

/* Weather DTO */
export interface WeatherState {
  userLocation: string;
  query: string;
  weatherData: {
    nameOfCity: string;
    countryShort: string;
    description: string;
    temp: number;
    feelsLike: number;
    tempMax: number;
    tempMin: number;
  }
  status: 'Loading' | 'Succeed' | 'Filed' | undefined
}

/* Initial State */
const initialState: WeatherState = {
  userLocation: "",
  query: "Tel Aviv",
  weatherData: {
    nameOfCity: "",
    countryShort: "",
    description: "",
    temp: 0,
    feelsLike: 0,
    tempMax: 0,
    tempMin: 0,
  },
  status: undefined,
};

/* Get weather data by query */
export const getWeatherByQuery = createAsyncThunk(
  'weather/getWeatherDataByLocation',
  async (location: string) => {
    const result = await getWeatherDataByLocation(location)
    return result.data;
  }
)

/* Get weather data by user location */
export const getWeatherByUserLocation = createAsyncThunk(
  'weather/getWeatherDataByUserLocation',
  async (obj: { latitude: number, longitude: number }): Promise<any> => {
    const response = await getWeatherDataByUserLocation(obj.latitude, obj.longitude);
    return response?.data;
  }
)


export const weatherSlice = createSlice({
  name: 'weather',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    updateUserQuery: (state, action) => {
      state.query = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {

    builder.addCase(getWeatherByQuery.pending, (state) => {
      state.status = "Loading";
    })
      .addCase(getWeatherByQuery.rejected, (state) => {
        state.status = "Filed"
      })
      .addCase(getWeatherByQuery.fulfilled, (state, { payload: data }) => {
        state.status = "Succeed"
        state.weatherData.nameOfCity = data.name;
        state.weatherData.countryShort = data.sys.country;
        state.weatherData.description = data.weather[0].description;
        state.weatherData.temp = data.main.temp;
        state.weatherData.feelsLike = data.main.feels_like;
        state.weatherData.tempMax = data.main.temp_max;
        state.weatherData.tempMin = data.main.temp_min;
      })



    // builder.addCase(getWeatherByUserLocation.pending, (state) => {
    //   state.status = 'loading';
    // })
    // builder.addCase(getWeatherByUserLocation.fulfilled, (state, { payload }) => {
    //   state.status = 'done';
    // })
    // builder.addCase(getWeatherByUserLocation.rejected, (state, { payload }) => {
    //   state.status = 'filed';
    // });

  },
});

export const { updateUserQuery } = weatherSlice.actions;

export default weatherSlice.reducer;